name: Update Blog Posts with Date

on:
  push:
    paths:
      - 'posts.json'

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update posts.json with current date and time
        run: |
          node -e '
            const fs = require("fs");
            const path = require("path");
            const postsPath = path.join(__dirname, "posts.json");
            const posts = JSON.parse(fs.readFileSync(postsPath, "utf8"));

            // Add date to posts without date
            posts.posts = posts.posts.map((post) => {
              if (!post.date) {
                post.date = new Date().toISOString();
              }
              return post;
            });

            fs.writeFileSync(postsPath, JSON.stringify(posts, null, 2), "utf8");
          '

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts.json
          git commit -m "Automatically add date and time to new blog posts" || exit 0
          git push
